#!/bin/sh
# PORTMASTER: chrono, Chrono Trigger.sh
# Generated by nxbootstrap. All lifecycle logic stays in chrono/run.sh.

PORT_ID=chrono
PORT_TITLE='Chrono Trigger'

ORIGINAL_SELF=$0
ORIGINAL_DIR=$(CDPATH= cd -- "$(dirname -- "$ORIGINAL_SELF")" 2>/dev/null && pwd -P) ||
  ORIGINAL_DIR=.
SELF=$ORIGINAL_SELF
if [ -L "$SELF" ]; then
  if command -v readlink >/dev/null 2>&1; then
    RESOLVED=$(readlink -f -- "$SELF" 2>/dev/null || true)
    if [ -n "$RESOLVED" ]; then
      SELF=$RESOLVED
    else
      link_depth=0
      while [ -L "$SELF" ] && [ "$link_depth" -lt 16 ]; do
        LINK=$(readlink -- "$SELF" 2>/dev/null || true)
        case "$LINK" in
          /*) SELF=$LINK ;;
          ?*) SELF=$(dirname -- "$SELF")/$LINK ;;
          *) break ;;
        esac
        link_depth=$((link_depth + 1))
      done
      [ "$link_depth" -lt 16 ] || exit 1
    fi
  fi
fi
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$SELF")" 2>/dev/null && pwd -P) ||
  exit 1

TRIED=
try_launcher() {
  candidate=$1
  shift
  TRIED="${TRIED}${TRIED:+
}$candidate"
  if [ -f "$candidate" ] && [ ! -L "$candidate" ]; then
    exec bash "$candidate" "$@"
  fi
}

# Relative discovery covers copies/symlinks in ports, ports_scripts and a few
# nested frontend layouts without guessing which CFW owns the card.
cursor=$SCRIPT_DIR
depth=0
while [ "$depth" -lt 5 ]; do
  try_launcher "$cursor/$PORT_ID/run.sh" "$@"
  try_launcher "$cursor/ports/$PORT_ID/run.sh" "$@"
  try_launcher "$cursor/Ports/$PORT_ID/run.sh" "$@"
  parent=$(dirname -- "$cursor")
  [ "$parent" != "$cursor" ] || break
  cursor=$parent
  depth=$((depth + 1))
done

for rom_root in \
  /roms /roms2 /storage/roms /userdata/roms \
  /mnt/mmc /mnt/mmc/roms /mnt/mmc/ROMS \
  /mnt/sdcard /mnt/sdcard/roms /mnt/sdcard/ROMS
do
  try_launcher "$rom_root/ports/$PORT_ID/run.sh" "$@"
  try_launcher "$rom_root/Ports/$PORT_ID/run.sh" "$@"
done

message="$PORT_TITLE: $PORT_ID/run.sh not found"
details="launcher=$ORIGINAL_SELF resolved=$SELF
paths tried:
$TRIED"
printf '%s\n%s\n' "$message" "$details" >&2
umask 077
for log in \
  "$ORIGINAL_DIR/${PORT_ID}-launcher-error.$$.log" \
  "$SCRIPT_DIR/${PORT_ID}-launcher-error.$$.log" \
  "${TMPDIR:-/tmp}/${PORT_ID}-launcher-error.$$.log"
do
  if (set -C; printf '%s\n%s\n' "$message" "$details" > "$log") 2>/dev/null; then
    for tty in /dev/tty0 /dev/console; do
      if [ -c "$tty" ] && [ ! -L "$tty" ]; then
        printf '%s; details: %s\n' "$message" "$log" > "$tty" 2>/dev/null && break
      fi
    done
    break
  fi
done
exit 1
