#!/usr/bin/env bash
# Hermetic release gate. It never executes owner game code.
set -euo pipefail

export LC_ALL=C
export TZ=UTC
export PYTHONDONTWRITEBYTECODE=1

PORT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
cd "$PORT_DIR"

for script in build_universal.sh "Chrono Trigger.sh" \
              nxextract/run-extractor.sh nxextract/nxextract-runtime-env.sh \
              package/build-package.sh; do
  bash -n "$script"
done

python3 -B nxextract/nxextract.py recipe-check --recipe extractor.json

TEST_ROOT=$(mktemp -d "${TMPDIR:-/tmp}/chrono-host.XXXXXX")
cleanup() {
  case $TEST_ROOT in
    "${TMPDIR:-/tmp}"/chrono-host.*) rm -rf -- "$TEST_ROOT" ;;
    *) printf 'refusing unsafe cleanup target: %s\n' "$TEST_ROOT" >&2 ;;
  esac
}
trap cleanup EXIT INT TERM

python3 -B framework/nxbootstrap/tools/generate-port.py \
  nxport.json --output "$TEST_ROOT/generated"
cmp -s "Chrono Trigger.sh" "$TEST_ROOT/generated/Chrono Trigger.sh"
cmp -s nxport.json "$TEST_ROOT/generated/chrono/nxport.json"

grep -Fq 'generated by nxbootstrap 0.6.3' "Chrono Trigger.sh"
grep -Fq 'stat -L -t /proc/self/fd/9' "Chrono Trigger.sh"
grep -Fq '"$NXBOOTSTRAP_LOCK_FILE" -ef /proc/self/fd/9' "Chrono Trigger.sh"
if grep -Eq '^[[:space:]]*[^#].*stat[[:space:]]+-c([[:space:]]|$)' \
    "Chrono Trigger.sh"; then
  printf '%s\n' 'GNU-only stat -c returned to the launcher' >&2
  exit 1
fi

cc -D_POSIX_C_SOURCE=200809L -std=c11 -Wall -Wextra -Werror \
  -Isrc src/chrono_language.c tests/test_chrono_language.c \
  -o "$TEST_ROOT/test-chrono-language"
"$TEST_ROOT/test-chrono-language"

if [[ -f chrono-nextos ]]; then
  MACHINE=$(readelf -h chrono-nextos |
    sed -n 's/^[[:space:]]*Machine:[[:space:]]*//p')
  [[ $MACHINE == AArch64 ]]
  MAX_GLIBC=$(readelf --version-info chrono-nextos 2>/dev/null |
    grep -oE 'GLIBC_[0-9]+([.][0-9]+)*' | sort -Vu | tail -1)
  [[ -n $MAX_GLIBC ]]
  VERSION=${MAX_GLIBC#GLIBC_}
  MAJOR=${VERSION%%.*}
  MINOR=${VERSION#*.}; MINOR=${MINOR%%.*}
  (( MAJOR < 2 || (MAJOR == 2 && MINOR <= 30) ))
fi

if [[ -e nxbootstrap.sh || -e chrono-universal ]]; then
  printf '%s\n' 'legacy launcher layer or executable is still present' >&2
  exit 1
fi

git diff --check
printf '%s\n' \
  'CHRONO HOST GATE: PASS' \
  'physical_device_evidence=0 proprietary_payload_packaged=0 guest_execution=0'
